services:
  paddleocr-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: paddleocr-api

    ports:
      - "6868:6868"

    volumes:
      - ./input:/app/input
      - ./output:/app/output

    environment:
      PYTHONUNBUFFERED: "1"